#!/bin/bash

###############################################################################
#   Bash Prompt
###############################################################################
. bash_prompt

bashrcLocation=~/.bashrc
bashPromptString="source ~/.bash_prompt"

if ! grep -q $bashPromptString $bashPromptLocation; then
    echo $bashPromptString >> $bashPromptLocation
fi
###############################################################################
